version: '3'
services:
  mTab:
    image: itushan/php74:1.3
    container_name: mTabServers
    ports:
      - "3321:80"
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: 172.17.0.1
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mtab
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    restart: always
